import React from 'react';
import { ShieldAlert } from 'lucide-react';

export const WarningBanner: React.FC = () => {
  return (
    <div className="bg-amber-100 border-l-4 border-amber-500 text-amber-900 p-4 mb-6 flex items-start rounded-r-xl shadow-sm">
      <ShieldAlert className="w-6 h-6 mr-3 shrink-0 text-amber-600" />
      <div>
        <p className="font-bold text-sm">⚠️ AI-assisted draft — Physician verification required before clinical use.</p>
        <p className="text-xs mt-1 opacity-90">This content was generated by an AI assistant and must be reviewed and verified by a licensed medical professional.</p>
      </div>
    </div>
  );
};
